---
repo: AdobeDocs/commerce-on-cloud.en
url: https://experienceleague.adobe.com/en/docs/commerce-on-cloud/user-guide/overview
exclude:
  - Rakefile
  - tmp
  - Gemfile
  - Gemfile.lock
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
